<?php
if ( ! defined( 'WP_ENV' ) and function_exists( 'acf_add_local_field_group' ) ) {

    acf_add_local_field_group( array(
        'key'                   => 'group_573e0af187c60',
        'title'                 => 'Custom Content',
        'fields'                => array(
            array(
                'key'               => 'field_573e0b06159d6',
                'label'             => 'Content Rows',
                'name'              => 'content_rows',
                'type'              => 'flexible_content',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'button_label'      => 'Add Content Row',
                'min'               => '',
                'max'               => '',
                'layouts'           => array(
                    array(
                        'key'        => '573e0b167c6da',
                        'name'       => 'columns',
                        'label'      => 'Columns Row',
                        'display'    => 'block',
                        'sub_fields' => array(
                            array(
                                'key'               => 'field_57a3969af2b2b',
                                'label'             => 'Breakpoint Size',
                                'name'              => 'col_size',
                                'type'              => 'select',
                                'instructions'      => '',
                                'required'          => 0,
                                'conditional_logic' => 0,
                                'wrapper'           => array(
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ),
                                'choices'           => array(
                                    'lg' => 'Large',
                                    'md' => 'Medium',
                                    'sm' => 'Small',
                                    'xs' => 'Extra Small',
                                ),
                                'default_value'     => array(
                                    0 => 'md',
                                ),
                                'allow_null'        => 0,
                                'multiple'          => 0,
                                'ui'                => 0,
                                'ajax'              => 0,
                                'placeholder'       => '',
                                'disabled'          => 0,
                                'readonly'          => 0,
                            ),
                            array(
                                'key'               => 'field_573e0b35159d7',
                                'label'             => 'Columns',
                                'name'              => 'columns',
                                'type'              => 'repeater',
                                'instructions'      => '',
                                'required'          => 0,
                                'conditional_logic' => 0,
                                'wrapper'           => array(
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ),
                                'collapsed'         => '',
                                'min'               => 1,
                                'max'               => 6,
                                'layout'            => 'block',
                                'button_label'      => 'Add Column',
                                'sub_fields'        => array(
                                    array(
                                        'key'               => 'field_573e0b5c159d8',
                                        'label'             => 'Column Content',
                                        'name'              => 'column_content',
                                        'type'              => 'wysiwyg',
                                        'instructions'      => '',
                                        'required'          => 0,
                                        'conditional_logic' => 0,
                                        'wrapper'           => array(
                                            'width' => '',
                                            'class' => '',
                                            'id'    => '',
                                        ),
                                        'default_value'     => '',
                                        'tabs'              => 'all',
                                        'toolbar'           => 'full',
                                        'media_upload'      => 1,
                                    ),
                                ),
                            ),
                        ),
                        'min'        => '',
                        'max'        => '',
                    ),
                    array(
                        'key'        => '573e1d6947c6c',
                        'name'       => 'slideshow',
                        'label'      => 'Slideshow',
                        'display'    => 'block',
                        'sub_fields' => array(
                            array(
                                'key'               => 'field_573e1d7947c6d',
                                'label'             => 'Slides',
                                'name'              => 'slides',
                                'type'              => 'repeater',
                                'instructions'      => '',
                                'required'          => '',
                                'conditional_logic' => '',
                                'wrapper'           => array(
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ),
                                'collapsed'         => '',
                                'min'               => 1,
                                'max'               => '',
                                'layout'            => '',
                                'button_label'      => 'Add Slide',
                                'sub_fields'        => array(
                                    array(
                                        'key'               => 'field_573e1dda47c6e',
                                        'label'             => 'Slide Image',
                                        'name'              => 'slide_image',
                                        'type'              => 'image',
                                        'instructions'      => '',
                                        'required'          => 0,
                                        'conditional_logic' => 0,
                                        'wrapper'           => array(
                                            'width' => '',
                                            'class' => '',
                                            'id'    => '',
                                        ),
                                        'return_format'     => 'array',
                                        'preview_size'      => 'thumbnail',
                                        'library'           => 'all',
                                        'min_width'         => '',
                                        'min_height'        => '',
                                        'min_size'          => '',
                                        'max_width'         => '',
                                        'max_height'        => '',
                                        'max_size'          => '',
                                        'mime_types'        => '',
                                    ),
                                ),
                            ),
                        ),
                        'min'        => '',
                        'max'        => '',
                    ),
                    array(
                        'key'        => '57a3920ed9c78',
                        'name'       => 'tabs',
                        'label'      => 'Tabs Row',
                        'display'    => 'block',
                        'sub_fields' => array(
                            array(
                                'key'               => 'field_57a3a0ce16d8f',
                                'label'             => 'Tab Position',
                                'name'              => 'tab_pos',
                                'type'              => 'select',
                                'instructions'      => '',
                                'required'          => 1,
                                'conditional_logic' => 0,
                                'wrapper'           => array(
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ),
                                'choices'           => array(
                                    'top'  => 'Top',
                                    'side' => 'Side',
                                ),
                                'default_value'     => array(),
                                'allow_null'        => 0,
                                'multiple'          => 0,
                                'ui'                => 0,
                                'ajax'              => 0,
                                'placeholder'       => '',
                                'disabled'          => 0,
                                'readonly'          => 0,
                            ),
                            array(
                                'key'               => 'field_57a39227d9c79',
                                'label'             => 'Tabs',
                                'name'              => 'tabs',
                                'type'              => 'repeater',
                                'instructions'      => '',
                                'required'          => 1,
                                'conditional_logic' => 0,
                                'wrapper'           => array(
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ),
                                'collapsed'         => '',
                                'min'               => 2,
                                'max'               => 6,
                                'layout'            => 'block',
                                'button_label'      => 'Add Tab',
                                'sub_fields'        => array(
                                    array(
                                        'key'               => 'field_57a3927bd9c7a',
                                        'label'             => 'Tab Title',
                                        'name'              => 'tab_button',
                                        'type'              => 'text',
                                        'instructions'      => '',
                                        'required'          => 0,
                                        'conditional_logic' => 0,
                                        'wrapper'           => array(
                                            'width' => '',
                                            'class' => '',
                                            'id'    => '',
                                        ),
                                        'default_value'     => '',
                                        'placeholder'       => '',
                                        'prepend'           => '',
                                        'append'            => '',
                                        'maxlength'         => '',
                                        'readonly'          => 0,
                                        'disabled'          => 0,
                                    ),
                                    array(
                                        'key'               => 'field_57a3929dd9c7b',
                                        'label'             => 'Tab Content',
                                        'name'              => 'tab_content',
                                        'type'              => 'wysiwyg',
                                        'instructions'      => '',
                                        'required'          => 0,
                                        'conditional_logic' => 0,
                                        'wrapper'           => array(
                                            'width' => '',
                                            'class' => '',
                                            'id'    => '',
                                        ),
                                        'default_value'     => '',
                                        'tabs'              => 'all',
                                        'toolbar'           => 'full',
                                        'media_upload'      => 1,
                                    ),
                                ),
                            ),
                        ),
                        'min'        => '',
                        'max'        => '',
                    ),
                    array(
                        'key'        => '57a4aca0e07a5',
                        'name'       => 'accordion',
                        'label'      => 'Accordion Row',
                        'display'    => 'block',
                        'sub_fields' => array(
                            array(
                                'key'               => 'field_57a4b1e50234d',
                                'label'             => 'Open First',
                                'name'              => 'open_first',
                                'type'              => 'true_false',
                                'instructions'      => '',
                                'required'          => 0,
                                'conditional_logic' => 0,
                                'wrapper'           => array(
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ),
                                'message'           => 'Open first panel on page load',
                                'default_value'     => 1,
                            ),
                            array(
                                'key'               => 'field_57a4acbde07a6',
                                'label'             => 'Accordion',
                                'name'              => 'accordion',
                                'type'              => 'repeater',
                                'instructions'      => '',
                                'required'          => 1,
                                'conditional_logic' => 0,
                                'wrapper'           => array(
                                    'width' => '',
                                    'class' => '',
                                    'id'    => '',
                                ),
                                'collapsed'         => '',
                                'min'               => 2,
                                'max'               => '',
                                'layout'            => 'block',
                                'button_label'      => 'Add Accordion Panel',
                                'sub_fields'        => array(
                                    array(
                                        'key'               => 'field_57a4accbe07a7',
                                        'label'             => 'Accordion Title',
                                        'name'              => 'accordion_title',
                                        'type'              => 'text',
                                        'instructions'      => '',
                                        'required'          => 1,
                                        'conditional_logic' => 0,
                                        'wrapper'           => array(
                                            'width' => '',
                                            'class' => '',
                                            'id'    => '',
                                        ),
                                        'default_value'     => '',
                                        'placeholder'       => '',
                                        'prepend'           => '',
                                        'append'            => '',
                                        'maxlength'         => '',
                                        'readonly'          => 0,
                                        'disabled'          => 0,
                                    ),
                                    array(
                                        'key'               => 'field_57a4acd8e07a8',
                                        'label'             => 'Accordion Content',
                                        'name'              => 'accordion_content',
                                        'type'              => 'wysiwyg',
                                        'instructions'      => '',
                                        'required'          => 1,
                                        'conditional_logic' => 0,
                                        'wrapper'           => array(
                                            'width' => '',
                                            'class' => '',
                                            'id'    => '',
                                        ),
                                        'default_value'     => '',
                                        'tabs'              => 'all',
                                        'toolbar'           => 'full',
                                        'media_upload'      => 1,
                                    ),
                                ),
                            ),
                        ),
                        'min'        => '',
                        'max'        => '',
                    ),
                ),
            ),
        ),
        'location'              => array(
            array(
              array(
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'templates/template-page-builder.php',
              ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
      		0 => 'the_content',
      	),
        'active'                => 1,
        'description'           => '',
    ) );

    acf_add_local_field_group( array(
        'key'                   => 'group_57a9f4dce4efe',
        'title'                 => 'Site Options',
        'fields'                => array(
            array(
                'key'               => 'field_57a9f4f464bb2',
                'label'             => 'Site Layout',
                'name'              => 'site_layout',
                'type'              => 'select',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'choices'           => array(
                    'container'       => 'Centered Container',
                    'container-fluid' => 'Full Screen (Fluid)',
                ),
                'default_value'     => array(),
                'allow_null'        => 0,
                'multiple'          => 0,
                'ui'                => 0,
                'ajax'              => 0,
                'placeholder'       => '',
                'disabled'          => 0,
                'readonly'          => 0,
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'options_page',
                    'operator' => '==',
                    'value'    => 'theme-general-options',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => 1,
        'description'           => '',
    ) );

}
